### ISSUE TITLE
Pre conference dinner on Monday

### ISSUE THREAD

**Issue by xml-project** [xproc/Workshop-2018-02#2]
@Gertone @rdeltour @bertfrees @gimsieke @mkraetke @eriksiegel @ndw @mricaud @cmarchand @dmj @sgmlguru 

Since some of you might arrive at Prague on Monday, is anyone interested in a preconference dinner on Monday. 
If so, please comment on this issue, so I could book a table somewhere.

**Comment by rdeltour** [comment]
I will land at 19:40, so given the time to reach the hotel and drop my stuff it would probably be too late for dinner. But I’m happy to join you for a drink wherever you will be!

**Comment by sgmlguru** [comment]
Hi,

Great idea. How about the Sklep some time in the evening? Decent food and
beer, and close to the venue.

I'd expect to be at my hotel around 17.30 or so.

Best,

/Ari

**Comment by gimsieke** [comment]
@mkraetke and I will arrive at the bus station at 10:40 on Tuesday. So we won’t be able to participate in the `<p:reconference-dinner/>`.

**Comment by Gertone** [comment]
That is a <p:itty/>

----- Oorspronkelijk bericht -----
Van: Gerrit Imsieke <notifications@github.com>
Aan: xproc/Workshop-2018-02 <Workshop-2018-02@noreply.github.com>
Cc: Gertone <geert@gbormans.telenet.be>, Mention <mention@noreply.github.com>
Verzonden: Wed, 31 Jan 2018 12:05:35 +0100 (CET)
Onderwerp: Re: [xproc/Workshop-2018-02] Pre conference dinner on Monday (#2)

@mkraetke and I will arrive at the bus station at 10:40 on Tuesday. So we won’t be able to participate in the `<p:reconference-dinner/>`.

**Comment by sgmlguru** [comment]
<p:groan/>

On 31 Jan 2018 12:15, "Gertone" <notifications@github.com> wrote:

That is a <p:itty/>

----- Oorspronkelijk bericht -----
Van: Gerrit Imsieke <notifications@github.com>
Aan: xproc/Workshop-2018-02 <Workshop-2018-02@noreply.github.com>
Cc: Gertone <geert@gbormans.telenet.be>, Mention <mention@noreply.github.com
>
Verzonden: Wed, 31 Jan 2018 12:05:35 +0100 (CET)
Onderwerp: Re: [xproc/Workshop-2018-02] Pre conference dinner on Monday (#2)


@mkraetke and I will arrive at the bus station at 10:40 on Tuesday. So we
won’t be able to participate in the `<p:reconference-dinner/>`.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/xproc/Workshop-2018-02/issues/2#issuecomment-361899450

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xproc/Workshop-2018-02/issues/2#issuecomment-361901839>,
or mute the thread

**Comment by xatapult** [comment]
I arrive very late Monday evening. CU Tuesday

 

Erik

 

Van: Achim Berndzen [mailto:notifications@github.com] 
Verzonden: woensdag 31 januari 2018 11:54
Aan: xproc/Workshop-2018-02 <Workshop-2018-02@noreply.github.com>
CC: eriksiegel <erik@xatapult.nl>; Mention <mention@noreply.github.com>
Onderwerp: [xproc/Workshop-2018-02] Pre conference dinner on Monday (#2)

 

@Gertone <https://github.com/gertone>  @rdeltour <https://github.com/rdeltour>  @bertfrees <https://github.com/bertfrees>  @gimsieke <https://github.com/gimsieke>  @mkraetke <https://github.com/mkraetke>  @eriksiegel <https://github.com/eriksiegel>  @ndw <https://github.com/ndw>  @mricaud <https://github.com/mricaud>  @cmarchand <https://github.com/cmarchand>  @dmj <https://github.com/dmj>  @sgmlguru <https://github.com/sgmlguru> 

Since some of you might arrive at Prague on Monday, is anyone interested in a preconference dinner on Monday.
If so, please comment on this issue, so I could book a table somewhere.

**Comment by cmarchand** [comment]
We will land too late. But our hotel is just near Sklep... maybe we will join you there. But do not expect us.

**Comment by ndw** [comment]
Bethan and I are arriving in the evening on Monday. We'll stop by the Sklep if we're up for it, though it's more likely to be drinks and/or dessert than dinner. If we don't make it, see you on Tuesday!

**Comment by dmj** [comment]
I arrive around 8 p.m. and would join if health permits. Combatting a nasty cold right now and dunno how it will be on monday.

**Comment by xml-project** [comment]
It's official: Ari and I will have dinner at [Sklep](http://wwww.restauracesklep.cz/en/) 7pm local time.
If you wan't to join us, please do. 
CU!

**Comment by cmarchand** [comment]
Seems this issue will never be solved !
Have a drink for those who won't be able to join...
;)

**Comment by xml-project** [comment]
We have a plan to fix it, but we need your help, you know .... @cmarchand

**Comment by bertfrees** [comment]
I arrive very late.

**Comment by Gertone** [comment]
Ok, did not make it to the drink either. I broke a tooth right before I was about to start driving. ( no, i was not trying to eat my passport ) Took me the afternoon to get a dentist who could work on it. Stuck in Wurzburg now. Will arrive a bit late for the morning session, see you all in the afternoon

**Comment by xml-project** [comment]
happy to close the first issue of the meeting after successful work.
